kind: Service
apiVersion: v1
metadata:
  name:  techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app:  techtrends
  type:  {{ .Values.service.type }}
  ports:
  - port:  {{ .Values.service.port }}
    targetPort:  {{ .Values.service.targetPort }}
    protocol: {{ .Values.service.protocol }}